# Generated by Django 4.2.8 on 2025-12-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('service', models.CharField(choices=[('m365', 'Microsoft 365'), ('office', 'Văn phòng ảo'), ('digital', 'Chữ ký số & Hoá đơn'), ('all', 'Tất cả dịch vụ')], max_length=20, verbose_name='Dịch vụ')),
                ('message', models.TextField(blank=True, verbose_name='Nội dung')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('contacted', 'Đã liên hệ'), ('converted', 'Đã chuyển đổi'), ('closed', 'Đã đóng')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú nội bộ', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Yêu cầu tư vấn',
                'verbose_name_plural': 'Yêu cầu tư vấn',
                'ordering': ['-created_at'],
            },
        ),
    ]
